name: staging deployment
on: push

jobs:
    deploy-staging:
        name: deploy staging
        runs-on: ubuntu-latest
        needs: [build, test]

        steps:
        - name: recover build
          uses: actions/download-artifacts@v2
          with:
              name: build
        
        - name: deploy to staging
          uses: nogsantos/scp-deploy@master
          with:
              src: ./build/*
              host: ${{ secrets.SSH_HOST }}
              remote: ${{ secrets.SSH_DIR }}/${{ secrets.STAGING_DIR }}
              port: ${{ secrets.SSH_PORT }}
              user: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_KEY }}

