name: production deploy
on:
    push:
        branches:
        - master

jobs:
    deploy-prod:
        name: deploy prod
        runs-on: ubuntu-latest
        needs: [build, test]

        steps:
        - name: recover build
          uses: actions/download-artifact@v2
          with:
              name: build
        
        - name: deploy to prod
          uses: nogsantos/scp-deploy@master
          with:
              src: ./build/*
              host: ${{ secrets.SSH_HOST }}
              remote: ${{ secrets.SSH_DIR }}/${{ secrets.PROD_DIR }}
              port: ${{ secrets.SSH_PORT }}
              user: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_KEY }}

