name: personal site ci/cd
on: push

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        env:
            NODE_VERSION: 14.18.0

        steps:
        - name: checkout repository
          uses: actions/checkout@v2

        - name: load/save cache
          uses: actions/cache@v2
          with:
              path: |
                  node_modules
                  .pnp
                  .pnp.js
              key: ${{ runner.os }}-package-lock-${{ hashFiles('**/package-lock.json') }}-v1
              restore-keys: |
                  ${{ runner.os }}-package-lock-

        - name: setup node.js
          uses: actions/setup-node@v1
          with:
              node-version: ${{ env.NODE_VERSION }}

        - name: install dependencies
          run: npm install

        - name: build
          run: npm run build

        - name: archive build
          uses: actions/upload-artifact@v2
          with:
              name: build
              path: *

    test:
        name: test
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: recover build
          uses: actions/download-artifact@v2
          with:
              name: build

        - name: setup node.js
          uses: actions/setup-node@v1
          with:
              node-version: ${{ needs.jobs.build.env.NODE_VERSION }}

        - name: run tests
          run: npm test
        
    deploy-prod:
        name: deploy prod
        runs-on: ubuntu-latest
        needs: [build, test]

        steps:
        - name: recover build
          uses: actions/download-artifact@v2
          with:
              name: build
        
        - name: deploy to prod
          uses: nogsantos/scp-deploy@master
          with:
              src: ./build/*
              host: ${{ secrets.SSH_HOST }}
              remote: ${{ secrets.SSH_DIR }}/${{ secrets.PROD_DIR }}
              port: ${{ secrets.SSH_PORT }}
              user: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_KEY }}

    deploy-staging:
        name: deploy staging
        runs-on: ubuntu-latest
        needs: [build, test]

        steps:
        - name: recover build
          uses: actions/download-artifacts@v2
          with:
              name: build
        
        - name: deploy to staging
          uses: nogsantos/scp-deploy@master
          with:
              src: ./build/*
              host: ${{ secrets.SSH_HOST }}
              remote: ${{ secrets.SSH_DIR }}/${{ secrets.STAGING_DIR }}
              port: ${{ secrets.SSH_PORT }}
              user: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_KEY }}
workflows:
    build_and_test:
        name: build and test
        jobs:
        - build
        - test:
            requires:
            - build

    deploy_prod:
        name: production deployment
        jobs:
        - deploy-prod:
            requires:
            - build
            - test
        filters:
            branches:
                only: master

    deploy_staging:
        name: staging deployment
        jobs:
        - deploy-staging:
            requires:
            - build
            - test
        filters:
            branches:
                only: staging

